FROM python:3.6.14-alpine3.14

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir /opt/app
WORKDIR /opt/app

COPY scripts/*.py /opt/app

ENTRYPOINT ["python", "extract_request.py"]