{{- with .Values.db }}
  {{- if .enabled}}
  {{- if .secret.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: test-bpintegration-db-config{{ $.Values.global.env }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  DB_HOST: {{ (required " db host is mandatory" $.Values.global.integration.db_host) | b64enc }}
  DB_NAME: {{ (required "db name is mandatory" $.Values.global.integration.db_name) | b64enc }}
  DB_USERNAME: {{ (required "db username is mandatory" $.Values.global.integration.db_username) | b64enc }}
  DB_PASSWORD: {{ (required "db password is mandatory" $.Values.global.integration.db_password) | b64enc }}
  DB_PASSWORD_ROLE: {{ (required "test-bpintegration DB password is mandatory" $.Values.app.dbpass) | b64enc }}
  CAMUNDA_AS_PASSWORD: {{ (required "Camunda db pass is mandatory" $.Values.app.camunda.dbpass) | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}