{{- $keycloakUri := $.Values.global.infonova.keycloakUrl | default $.Values.global.infonova.url }}
{{- $keycloakRealmUri := print (required "Infonova url is mandatory" $keycloakUri) "/auth/realms/" (required "Realm is mandatory" $.Values.global.infonova_tenant.realm) }}

{{- with .Values.app }}
  {{- if .enabled}}
  {{- if .secret.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{$.Chart.Name }}{{ $.Values.global.env }}
type: Opaque
data:
  spring_security_oauth2_resourceserver_jwt_issuer-uri: {{  $keycloakRealmUri | b64enc }}
  spring_security_oauth2_client_registration_infonova_client-secret: {{ (required "Secret for client communicating to infonova is mandatory" .appClientSecret) | b64enc }}
  spring_security_oauth2_client_provider_infonova_token-uri: {{ print $keycloakRealmUri "/protocol/openid-connect/token" | b64enc }}
  infonovaBaseUrl: {{ print $.Values.global.infonova.url "/r6-api" | b64enc }}
  infonovaMarketplaceUrl: {{ $.Values.global.infonova.marketplace.url | b64enc }}
  infonovaPartnerhubUrl: {{ $.Values.global.infonova.partnerhub.url | b64enc }}
  tenant_ws_name: {{ $.Values.global.infonova_tenant.tenantWs | b64enc }}
  tenant_name: {{ $.Values.global.infonova_tenant.tenant | b64enc }}
  cors_allowedOrigins: {{  $.Values.app.cors.allowedOrigins | b64enc }}
  cors_allowedHeaders: {{  $.Values.app.cors.allowedHeaders | b64enc }}
  cors_allowedMethods: {{  $.Values.app.cors.allowedMethods | b64enc }}
  camunda_dbdriver: {{ (required "Camunda db driver is mandatory" .camunda.dbdriver) | b64enc }}
  camunda_dburl: {{ (required "Camunda db url is mandatory" .camunda.dburl) | b64enc }}
  camunda_dbuser: {{ (required "Camunda db user is mandatory" .camunda.dbuser) | b64enc }}
  camunda_dbpass: {{ (required "Camunda db pass is mandatory" .camunda.dbpass) | b64enc }}
  spring_datasource_driver: {{ (required "test-bpintegration DB driver is mandatory" .dbdriver) | b64enc }}
  spring_datasource_url: {{ (required "test-bpintegration DB url is mandatory" .dburl) | b64enc }}
  spring_datasource_userName: {{ (required "test-bpintegration DB user is mandatory" .dbuser) | b64enc }}
  spring_datasource_password: {{ (required "test-bpintegration DB password is mandatory" .dbpass) | b64enc }}
  notification_smtp_password: {{ required "notification_smtp_password is mandatory" $.Values.global.infonova.notification_smtp.password | b64enc }}
  notification_smtp_marketplace_email: {{ required "notification_smtp_marketplace_email is mandatory" $.Values.global.infonova.notification_smtp.address | b64enc }}
  notification_smtp_replyTo: {{ required "notification_email_replyTo is mandatory" $.Values.global.infonova.notification_smtp.replyTo | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
