{{- if .Values.app.serviceAccount.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "app.serviceAccountName is mandatory" .Values.app.serviceAccountName }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "global.integration.gcpProxy.serviceAccount is mandatory" .Values.global.integration.gcpProxy.serviceAccount }}
{{- end }}